### ISSUE TITLE
After clicking on register or login the page simply refreshes

### ISSUE THREAD

**Issue by kaneru** [crestify/crestify#14]
I am able to open http://localhost:8000, the app seems to be running, but when I try to click on login or register a page simply refreshes.

[GIF with the issue, posted on imgur](https://imgur.com/a/IVGHh)

Thanks in advance.

**Comment by dhamaniasad** [comment]
Sorry to hear you're facing this issue. I was able to reproduce this locally, and I'm looking into it. I'll push out a fix ASAP.

**Comment by dhamaniasad** [comment]
This is proving interesting to debug. If I comment out `@anonymous_user_required` [here](https://github.com/mattupstate/flask-security/blob/develop/flask_security/views.py#L64), the login page renders. Investigating further.

**Comment by dhamaniasad** [comment]
This may be related to `Flask-Login`. [Source](https://github.com/mattupstate/flask-security/issues/446).

**Comment by dhamaniasad** [comment]
@kaneru This has been resolved and the changes are on the master branch now. Thanks for your patience with this issue resolution :)
