### ISSUE TITLE
Error with the installment process 

### ISSUE THREAD

**Issue by pawelorzech** [crestify/crestify#3]
Well... And now something is wrong later in the process. 

> [127.0.0.1:2222] out: building 'lxml.etree' extension
> [127.0.0.1:2222] out: 
> [127.0.0.1:2222] out: creating build/temp.linux-x86_64-2.7
> [127.0.0.1:2222] out: 
> [127.0.0.1:2222] out: creating build/temp.linux-x86_64-2.7/src
> [127.0.0.1:2222] out: 
> [127.0.0.1:2222] out: creating build/temp.linux-x86_64-2.7/src/lxml
> [127.0.0.1:2222] out: 
> [127.0.0.1:2222] out: x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/libxml2 -I/home/crestify/crestifyenv/build/lxml/src/lxml/includes -I/usr/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.linux-x86_64-2.7/src/lxml/lxml.etree.o -w
> [127.0.0.1:2222] out: 
> [127.0.0.1:2222] out: x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/src/lxml/lxml.etree.o -lxslt -lexslt -lxml2 -lz -lm -o build/lib.linux-x86_64-2.7/lxml/etree.so
> [127.0.0.1:2222] out: 
> [127.0.0.1:2222] out: /usr/bin/ld: cannot find -lz
> [127.0.0.1:2222] out: 
> [127.0.0.1:2222] out: collect2: error: ld returned 1 exit status
> [127.0.0.1:2222] out: 
> [127.0.0.1:2222] out: error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
> [127.0.0.1:2222] out: 
> [127.0.0.1:2222] out: ----------------------------------------
> [127.0.0.1:2222] out: Cleaning up...
> [127.0.0.1:2222] out: Command /home/crestify/crestifyenv/bin/python -c "import setuptools, tokenize;__file__='/home/crestify/crestifyenv/build/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-JeXaHG-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/crestify/crestifyenv/include/site/python2.7 failed with error code 1 in /home/crestify/crestifyenv/build/lxml
> [127.0.0.1:2222] out: Traceback (most recent call last):
> [127.0.0.1:2222] out:   File "/home/crestify/crestifyenv/bin/pip", line 11, in <module>
> [127.0.0.1:2222] out:     sys.exit(main())
> [127.0.0.1:2222] out:   File "/home/crestify/crestifyenv/local/lib/python2.7/site-packages/pip/__init__.py", line 185, in main
> [127.0.0.1:2222] out:     return command.main(cmd_args)
> [127.0.0.1:2222] out:   File "/home/crestify/crestifyenv/local/lib/python2.7/site-packages/pip/basecommand.py", line 163, in main
> [127.0.0.1:2222] out:     log_file_fp = open_logfile(log_file_fn, 'w')
> [127.0.0.1:2222] out:   File "/home/crestify/crestifyenv/local/lib/python2.7/site-packages/pip/basecommand.py", line 194, in open_logfile
> [127.0.0.1:2222] out:     os.makedirs(dirname)
> [127.0.0.1:2222] out:   File "/home/crestify/crestifyenv/lib/python2.7/os.py", line 157, in makedirs
> [127.0.0.1:2222] out:     mkdir(name, mode)
> [127.0.0.1:2222] out: OSError: [Errno 13] Permission denied: '/home/vagrant/.pip'
> [127.0.0.1:2222] out: 
> 
> 
> Fatal error: sudo() received nonzero return code 1 while executing!
> 
> Requested: pip install -r crestify/requirements.txt
> Executed: sudo -S -p 'sudo password:'  -u "crestify"  /bin/bash -c "cd /home/crestify >/dev/null && source crestifyenv/bin/activate && pip install -r crestify/requirements.txt"
> 
> Aborting.
> Disconnecting from 127.0.0.1:2222... done.

**Comment by dhamaniasad** [comment]
Thanks for reporting this! I'll look into it over the weekend and hopefully push a fix very soon! :)

**Comment by dhamaniasad** [comment]
I successfully reproduced this error locally. Investigating.

**Comment by dhamaniasad** [comment]
The error was a missing package. `libz-dev`. The master branch has the fix now.
