### ISSUE TITLE
Archiving locally

### ISSUE THREAD

**Issue by bdillahu** [crestify/crestify#5]
Am I correct (from a quick read through the archiving code) that there isn't a way to have the archive local, but rather relies on outside sources?

Sorry if I misunderstood.

**Comment by dhamaniasad** [comment]
Hi Bruce!

You are correct. Currently, there isn't a way to archive bookmarks locally.
If it's something you would like to have in Crestify, please open an issue
for the feature request and we'll take this further there :)

**Comment by dhamaniasad** [comment]
Moved to #6. I'll go ahead and close this issue.
